#include "gcode_exporter.h"

#include <iomanip>
#include <sstream>

static std::string format_coord(const std::string& fmt, double x, double y) {
    char buf[128];
    snprintf(buf, sizeof(buf), fmt.c_str(), x, y);
    return std::string(buf);
}

#include "path_optimizer.h"



bool GCodeExporter::exportGCode(const std::string& filepath,
                                const std::vector<DrawingGeometry>& geometries,
                                const DrawingAreaConfig& drawingArea,
                                int imageWidth,
                                int imageHeight,
                                const GCodeSettings& settings) {
    if (geometries.empty()) return false;

    std::ofstream out(filepath);
    if (!out.is_open()) {
        return false;
    }

    

    // Convert pixel coordinates to physical mm
    std::vector<DrawingGeometry> mmGeoms;
    mmGeoms.reserve(geometries.size());
    for (const auto& geom : geometries) {
        Path mmPath = pixel_path_to_mm(geom.path, imageWidth, imageHeight, drawingArea);
        if (!mmPath.empty()) {
            mmGeoms.push_back({mmPath, geom.penIndex, geom.groupIndex});
        }
    }

    // Prepare, filter and optimize paths
    std::map<int, std::vector<Path>> penPaths = PathOptimizer::preparePenPaths(
        mmGeoms, settings.minPathLength, settings.optimizePaths,
        settings.simplifyTolerance, settings.mergeTolerance);

    double h_mm = drawingArea.height_mm;
    double cx = settings.centerZero ? (drawingArea.width_mm / 2.0) : 0.0;
    double cy = settings.centerZero ? (drawingArea.height_mm / 2.0) : 0.0;

    out << "; G-code generated by imgto2d (DrawingBot V3 C++ port)\n";
    if (!settings.startGcode.empty()) out << settings.startGcode << "\n";
    out << settings.penUpCmd << "\n";

    for (auto it = penPaths.begin(); it != penPaths.end(); ++it) {
        int penIdx = it->first;
        std::string penName = "Pen_" + std::to_string(penIdx);
        
        if (!settings.startLayerCmd.empty()) {
            std::string cmd = settings.startLayerCmd;
            size_t pos = cmd.find("{pen}"); if(pos != std::string::npos) cmd.replace(pos, 5, penName);
            out << cmd << "\n";
        } else {
            out << "\n; --- LAYER: " << penName << " ---\n";
            out << "M0 ; PAUSE - Swap to pen '" << penName << "'\n";
        }

        for (const auto& path : it->second) {
            if (path.size() < 2) continue;

            int passes = std::max(1, settings.multipass);
            for (int p = 0; p < passes; ++p) {
                // Move to start
                double x0 = path[0].first - cx + settings.xOffset;
                double y0 = (h_mm - path[0].second) - cy + settings.yOffset; // Invert Y for CNC
                out << format_coord("G0 X%.3f Y%.3f\n", x0, y0);
                out << settings.penDownCmd << "\n";

                // Draw line
                for (std::size_t i = 1; i < path.size(); ++i) {
                    double xf = path[i].first - cx + settings.xOffset;
                    double yf = (h_mm - path[i].second) - cy + settings.yOffset;
                    out << format_coord("G1 X%.3f Y%.3f\n", xf, yf);
                }
                out << settings.penUpCmd << "\n";
            }
        }

        if (!settings.endLayerCmd.empty()) {
            out << settings.endLayerCmd << "\n";
        }
    }

    if (!settings.endGcode.empty()) out << settings.endGcode << "\n";
    
    return true;
}
