#include "export/gcode_exporter.h"
#include "export/path_optimizer.h"
#include <QFile>
#include <QTextStream>

bool GCodeExporter::exportGCode(const QString& filepath,
                                const QVector<DrawingGeometry>& geometries,
                                const DrawingAreaConfig& drawingArea,
                                int imageWidth,
                                int imageHeight,
                                const GCodeSettings& settings) {
    if (geometries.isEmpty()) return false;

    QFile file(filepath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        return false;
    }

    QTextStream out(&file);

    // Convert pixel coordinates to physical mm
    QVector<DrawingGeometry> mmGeoms;
    mmGeoms.reserve(geometries.size());
    for (const auto& geom : geometries) {
        Path mmPath = pixel_path_to_mm(geom.path, imageWidth, imageHeight, drawingArea);
        if (!mmPath.empty()) {
            mmGeoms.append({mmPath, geom.penIndex, geom.groupIndex});
        }
    }

    // Prepare, filter and optimize paths
    QMap<int, QVector<Path>> penPaths = PathOptimizer::preparePenPaths(
        mmGeoms, settings.minPathLength, settings.optimizePaths);

    double h_mm = drawingArea.height_mm;
    double cx = settings.centerZero ? (drawingArea.width_mm / 2.0) : 0.0;
    double cy = settings.centerZero ? (drawingArea.height_mm / 2.0) : 0.0;

    out << "; G-code generated by imgto2d (DrawingBot V3 C++ port)\n";
    if (!settings.startGcode.isEmpty()) out << settings.startGcode << "\n";
    out << settings.penUpCmd << "\n";

    for (auto it = penPaths.begin(); it != penPaths.end(); ++it) {
        int penIdx = it.key();
        QString penName = QString("Pen_%1").arg(penIdx);
        
        if (!settings.startLayerCmd.isEmpty()) {
            QString cmd = settings.startLayerCmd;
            cmd.replace("{pen}", penName);
            out << cmd << "\n";
        } else {
            out << "\n; --- LAYER: " << penName << " ---\n";
            out << "M0 ; PAUSE - Swap to pen '" << penName << "'\n";
        }

        for (const auto& path : it.value()) {
            if (path.size() < 2) continue;

            // Move to start
            double x0 = path[0].first - cx + settings.xOffset;
            double y0 = (h_mm - path[0].second) - cy + settings.yOffset; // Invert Y for CNC
            out << QString("G0 X%1 Y%2\n").arg(x0, 0, 'f', 3).arg(y0, 0, 'f', 3);
            out << settings.penDownCmd << "\n";

            // Draw line
            for (std::size_t i = 1; i < path.size(); ++i) {
                double xf = path[i].first - cx + settings.xOffset;
                double yf = (h_mm - path[i].second) - cy + settings.yOffset;
                out << QString("G1 X%1 Y%2\n").arg(xf, 0, 'f', 3).arg(yf, 0, 'f', 3);
            }
            out << settings.penUpCmd << "\n";
        }

        if (!settings.endLayerCmd.isEmpty()) {
            out << settings.endLayerCmd << "\n";
        }
    }

    if (!settings.endGcode.isEmpty()) out << settings.endGcode << "\n";
    
    return true;
}
