#include "../include/Exporters.h"
#include <fstream>
#include <iomanip>

namespace DrawingBot {

    void Exporter::exportSVG(const std::vector<PlotPath>& paths, const std::string& filename, int width, int height) {
        std::ofstream file(filename);
        if (!file.is_open()) return;

        file << "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 " << width << " " << height << "\">\n";
        file << "<style>path { fill: none; stroke-width: 1px; }</style>\n";
        
        std::string colors[] = {"#00FFFF", "#FF00FF", "#FFFF00", "#000000", "#FF0000", "#00FF00", "#0000FF"};

        for (const auto& path : paths) {
            if (path.points.empty()) continue;
            std::string color = colors[path.penIndex % 7];
            file << "<path stroke=\"" << color << "\" d=\"M " << path.points[0].x << " " << path.points[0].y;
            for (size_t i = 1; i < path.points.size(); i++) {
                file << " L " << path.points[i].x << " " << path.points[i].y;
            }
            file << "\" />\n";
        }
        
        file << "</svg>\n";
    }

    void Exporter::exportGCode(const std::vector<PlotPath>& paths, const std::string& filename, const GCodeSettings& settings, float width, float height, float feedrate) {
        std::ofstream file(filename);
        if (!file.is_open()) return;

        auto makeComment = [&](const std::string& msg) -> std::string {
            if (settings.commentType == 1) {
                return " (" + msg + ")";
            } else {
                return " ; " + msg;
            }
        };

        if (!settings.gcodeStart.empty()) {
            file << settings.gcodeStart << "\n";
        } else {
            file << makeComment("Generated by DrawingBot V3 Architecture") << "\n";
            file << "G21" << makeComment("Set units to millimeters") << "\n";
            file << "G90" << makeComment("Absolute positioning") << "\n";
        }
        
        file << "F" << std::fixed << std::setprecision(1) << feedrate << "\n";
        
        int currentPen = -1;
        float halfW = width / 2.0f;
        float halfH = height / 2.0f;

        for (const auto& path : paths) {
            if (path.points.empty()) continue;
            
            if (path.penIndex != currentPen) {
                if (currentPen != -1) {
                    if (!settings.gcodePenUp.empty()) {
                        file << settings.gcodePenUp << "\n";
                    } else {
                        file << "M3 S0" << makeComment("Pen Up") << "\n";
                    }
                    if (!settings.gcodeEndLayer.empty()) {
                        file << settings.gcodeEndLayer << "\n";
                    }
                }
                currentPen = path.penIndex;
                if (!settings.gcodeStartLayer.empty()) {
                    file << settings.gcodeStartLayer << "\n";
                }
                file << "M0" << makeComment("Pause for Tool Change to Pen " + std::to_string(currentPen + 1)) << "\n";
            }

            // Move to start (Pen Up)
            if (!settings.gcodePenUp.empty()) {
                file << settings.gcodePenUp << "\n";
            } else {
                file << "M3 S0" << makeComment("Pen Up") << "\n";
            }

            float startX = path.points[0].x + settings.offsetX;
            float startY = path.points[0].y + settings.offsetY;
            if (settings.centerZeroPoint) {
                startX -= halfW;
                startY -= halfH;
            }

            file << "G0 X" << std::fixed << std::setprecision(3) << startX 
                 << " Y" << startY << "\n";
                 
            // Drop Pen
            if (!settings.gcodePenDown.empty()) {
                file << settings.gcodePenDown << "\n";
            } else {
                file << "M3 S1000" << makeComment("Pen Down") << "\n";
            }
            
            // Trace path
            for (size_t i = 1; i < path.points.size(); i++) {
                float px = path.points[i].x + settings.offsetX;
                float py = path.points[i].y + settings.offsetY;
                if (settings.centerZeroPoint) {
                    px -= halfW;
                    py -= halfH;
                }
                file << "G1 X" << px << " Y" << py << "\n";
            }
        }
        
        if (currentPen != -1) {
            if (!settings.gcodePenUp.empty()) {
                file << settings.gcodePenUp << "\n";
            } else {
                file << "M3 S0" << makeComment("Pen Up") << "\n";
            }
            if (!settings.gcodeEndLayer.empty()) {
                file << settings.gcodeEndLayer << "\n";
            }
        }

        if (!settings.gcodeEnd.empty()) {
            file << settings.gcodeEnd << "\n";
        } else {
            file << "G0 X0 Y0" << makeComment("Return home") << "\n";
        }
    }

    void Exporter::exportHPGL(const std::vector<PlotPath>& paths, const std::string& filename, const HPGLSettings& settings) {
        std::ofstream file(filename);
        if (!file.is_open()) return;

        file << "IN;DF;PU;\n";
        if (settings.penVelocity > 0) {
            file << "VS" << settings.penVelocity << ";\n";
        }
        if (settings.penForce > 0) {
            file << "FS" << settings.penForce << ";\n";
        }
        
        int currentPen = -1;

        for (const auto& path : paths) {
            if (path.points.empty()) continue;
            
            if (path.penIndex != currentPen) {
                currentPen = path.penIndex;
                file << "SP" << (currentPen + settings.initialPen) << ";\n";
            }

            float startX = path.points[0].x;
            float startY = path.points[0].y;
            if (settings.xAxisMirror) startX = -startX;
            if (settings.yAxisMirror) startY = -startY;
            startX = std::clamp(startX, settings.hardClipMinX, settings.hardClipMaxX);
            startY = std::clamp(startY, settings.hardClipMinY, settings.hardClipMaxY);

            file << "PU" << (int)startX << "," << (int)startY << ";\n";
            file << "PD";
            for (size_t i = 1; i < path.points.size(); i++) {
                float px = path.points[i].x;
                float py = path.points[i].y;
                if (settings.xAxisMirror) px = -px;
                if (settings.yAxisMirror) py = -py;
                px = std::clamp(px, settings.hardClipMinX, settings.hardClipMaxX);
                py = std::clamp(py, settings.hardClipMinY, settings.hardClipMaxY);

                file << (int)px << "," << (int)py;
                if (i < path.points.size() - 1) file << ",";
            }
            file << ";\n";
        }
        
        file << "PU0,0;\n";
    }

} // namespace DrawingBot
