#include "../include/Exporters.h"
#include <fstream>
#include <iomanip>

namespace DrawingBot {

    void Exporter::exportSVG(const std::vector<PlotPath>& paths, const std::string& filename, int width, int height) {
        std::ofstream file(filename);
        if (!file.is_open()) return;

        file << "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 " << width << " " << height << "\">\n";
        file << "<style>path { fill: none; stroke-width: 1px; }</style>\n";
        
        std::string colors[] = {"#00FFFF", "#FF00FF", "#FFFF00", "#000000", "#FF0000", "#00FF00", "#0000FF"};

        for (const auto& path : paths) {
            if (path.points.empty()) continue;
            std::string color = colors[path.penIndex % 7];
            file << "<path stroke=\"" << color << "\" d=\"M " << path.points[0].x << " " << path.points[0].y;
            for (size_t i = 1; i < path.points.size(); i++) {
                file << " L " << path.points[i].x << " " << path.points[i].y;
            }
            file << "\" />\n";
        }
        
        file << "</svg>\n";
    }

    void Exporter::exportGCode(const std::vector<PlotPath>& paths, const std::string& filename, float feedrate) {
        std::ofstream file(filename);
        if (!file.is_open()) return;

        file << "; Generated by DrawingBot V3 Architecture\n";
        file << "G21 ; Set units to millimeters\n";
        file << "G90 ; Absolute positioning\n";
        file << "F" << std::fixed << std::setprecision(1) << feedrate << "\n";
        
        int currentPen = -1;

        for (const auto& path : paths) {
            if (path.points.empty()) continue;
            
            if (path.penIndex != currentPen) {
                if (currentPen != -1) file << "M3 S0 ; Pen Up\n";
                currentPen = path.penIndex;
                file << "M0 ; Pause for Tool Change to Pen " << (currentPen + 1) << "\n";
            }

            // Move to start (Pen Up)
            file << "M3 S0 ; Pen Up\n";
            file << "G0 X" << std::fixed << std::setprecision(3) << path.points[0].x 
                 << " Y" << path.points[0].y << "\n";
                 
            // Drop Pen
            file << "M3 S1000 ; Pen Down\n";
            
            // Trace path
            for (size_t i = 1; i < path.points.size(); i++) {
                file << "G1 X" << path.points[i].x << " Y" << path.points[i].y << "\n";
            }
        }
        
        file << "M3 S0 ; Pen Up\n";
        file << "G0 X0 Y0 ; Return home\n";
    }

    void Exporter::exportHPGL(const std::vector<PlotPath>& paths, const std::string& filename) {
        std::ofstream file(filename);
        if (!file.is_open()) return;

        file << "IN;DF;PU;\n";
        
        int currentPen = -1;

        for (const auto& path : paths) {
            if (path.points.empty()) continue;
            
            if (path.penIndex != currentPen) {
                currentPen = path.penIndex;
                file << "SP" << (currentPen + 1) << ";\n";
            }

            file << "PU" << (int)path.points[0].x << "," << (int)path.points[0].y << ";\n";
            file << "PD";
            for (size_t i = 1; i < path.points.size(); i++) {
                file << (int)path.points[i].x << "," << (int)path.points[i].y;
                if (i < path.points.size() - 1) file << ",";
            }
            file << ";\n";
        }
        
        file << "PU0,0;\n";
    }

} // namespace DrawingBot
