"""G-code export (DrawingBot V3 settings)."""

from __future__ import annotations

import math
from typing import Dict, List

from app.core.drawing_area import DrawingArea
from app.core.drawing_pen import DrawingPen
from app.export.path_export import prepare_pen_paths


def generate_gcode_lines(
    geometries,
    drawing_area: DrawingArea,
    active_pens: List[DrawingPen],
    gcode_settings: Dict,
    path_opt: Dict,
) -> List[str]:
    pen_paths = prepare_pen_paths(geometries, path_opt)
    h_mm = drawing_area.height_mm

    start_lines = (gcode_settings.get("start_gcode") or "G21\nG90").strip().split("\n")
    end_lines = (gcode_settings.get("end_gcode") or "M30").strip().split("\n")
    pen_down = gcode_settings.get("pen_down_cmd", "M3 S90").strip()
    pen_up = gcode_settings.get("pen_up_cmd", "M5").strip()
    start_layer = gcode_settings.get("start_layer_cmd", "").strip()
    end_layer = gcode_settings.get("end_layer_cmd", "").strip()
    x_off = float(gcode_settings.get("x_offset", 0.0))
    y_off = float(gcode_settings.get("y_offset", 0.0))
    center_zero = bool(gcode_settings.get("center_zero", False))
    cx = drawing_area.width_mm / 2.0 if center_zero else 0.0
    cy = drawing_area.height_mm / 2.0 if center_zero else 0.0

    lines = ["; G-code generated by DrawingBot V3 Python Edition"]
    lines.extend(start_lines)
    lines.append(pen_up)

    for pi in sorted(pen_paths.keys()):
        pen = active_pens[pi % len(active_pens)]
        if start_layer:
            lines.append(start_layer.replace("{pen}", pen.name))
        else:
            lines.append("")
            lines.append(f"; --- LAYER: {pen.name} ---")
            lines.append(f"M0 ; PAUSE - Swap to pen '{pen.name}'")

        for path in pen_paths[pi]:
            x0, y0 = path[0]
            x0, y0 = x0 - cx + x_off, (h_mm - y0) - cy + y_off
            lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
            lines.append(pen_down)
            for x, y in path[1:]:
                xf, yf = x - cx + x_off, (h_mm - y) - cy + y_off
                lines.append(f"G1 X{xf:.3f} Y{yf:.3f}")
            lines.append(pen_up)

        if end_layer:
            lines.append(end_layer)

    lines.extend(end_lines)
    return lines


def export_gcode(
    filepath: str,
    geometries,
    drawing_area: DrawingArea,
    active_pens: List[DrawingPen],
    gcode_settings: Dict,
    path_opt: Dict,
) -> None:
    lines = generate_gcode_lines(
        geometries,
        drawing_area,
        active_pens,
        gcode_settings,
        path_opt,
    )
    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
